<?php
/*
HLstatsX Community Edition - Real-time player and clan rankings and statistics
Copyleft (L) 2008-20XX Nicholas Hastings (nshastings@gmail.com)
http://www.hlxcommunity.com

HLstatsX Community Edition is a continuation of 
ELstatsNEO - Real-time player and clan rankings and statistics
Copyleft (L) 2008-20XX Malte Bayer (steam@neo-soft.org)
http://ovrsized.neo-soft.org/

ELstatsNEO is an very improved & enhanced - so called Ultra-Humongus Edition of HLstatsX
HLstatsX - Real-time player and clan rankings and statistics for Half-Life 2
http://www.hlstatsx.com/
Copyright (C) 2005-2007 Tobias Oetzel (Tobi@hlstatsx.com)

HLstatsX is an enhanced version of HLstats made by Simon Garner
HLstats - Real-time player and clan rankings and statistics for Half-Life
http://sourceforge.net/projects/hlstats/
Copyright (C) 2001  Simon Garner
            
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

For support and installation notes visit http://www.hlxcommunity.com
*/

    if (!defined('IN_HLSTATS')) {
        die('Do not access this file directly.');
    }
	
	/*
	 * HLstatsX Page Header This file will be inserted at the top of every page
	 * generated by HLstats. This file can contain PHP code.
	 */
	 
	// hit counter
	$db->query("UPDATE hlstats_Options SET value=value+1 WHERE keyname='counter_hits';"); 
  
	// visit counter
	if (isset($_COOKIE['ELstatsNEO_Visit']) && $_COOKIE['ELstatsNEO_Visit'] == 0) {
		// kein cookie gefunden, also visitcounter erh?hen und cookie setzen
		$db->query("UPDATE hlstats_Options SET value=value+1 WHERE keyname='counter_visits';");
		@setcookie('ELstatsNEO_Visit', '1', time() + ($g_options['counter_visit_timeout'] * 60), '/');   
	}
     
	global $game,$mode;

	// see if they have a defined style or a new style they'd like
	$selectedStyle = (isset($_COOKIE['style']) && $_COOKIE['style']) ? $_COOKIE['style'] : "";
	$selectedStyle = isset($_POST['stylesheet']) ? $_POST['stylesheet'] : $selectedStyle; 

	// if they do make sure it exists
	if(!empty($selectedStyle))
	{
		// this assumes that styles is up a directory from page_path, this might be a bad assumption
		$testfile=sprintf("%s/%s/%s", PAGE_PATH, '../styles', $selectedStyle);
		if(!file_exists($testfile))
		{
			$selectedStyle = "";
		}
	}
	
	// if they don't have one defined or the defined was is invalid use the default	
	if(empty($selectedStyle))
	{
		$selectedStyle=$g_options['style'];
	}	

	// if they had one, or tried to have one, set it to whatever we resolved it to
	if (isset($_POST['stylesheet']) || isset($_COOKIE['style']))
	{
		setcookie('style', $selectedStyle, time()+60*60*24*30);
	}

// this code here assumes that styles end with .css (the selector box for users and for admin does NOT check), someone may want to change this -octo
	// Determine if we have custom nav images available
    if ($selectedStyle) {
        $style = preg_replace('/\.css$/','',$selectedStyle);
    } else {
        $style = preg_replace('/\.css$/','',$g_options['style']);
    }
	$iconpath = IMAGE_PATH . "/icons";
	if (file_exists($iconpath . "/" . $style)) {
			$iconpath = $iconpath . "/" . $style;
	}
	
?>
<!DOCTYPE html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="hlstats.css?v=<?php echo intval(@filemtime(dirname(__DIR__) . '/hlstats.css')); ?>" />
	<link rel="stylesheet" type="text/css" href="styles/<?php echo $selectedStyle; ?>" />
	<link rel="stylesheet" type="text/css" href="css/SqueezeBox.css" />
	<!-- U R A SMACKHEAD -->

	<link rel="SHORTCUT ICON" href="favicon.ico" />
	<script type="text/javascript">
	window.HLX_I18N = <?php echo json_encode(array(
		'loading' => t('ui.loading'),
		'uploading' => t('ui.uploading'),
		'errorOccurred' => t('ui.error_occurred'),
		'kills' => t('literal.kills'),
		'deaths' => t('literal.deaths'),
		'players' => t('literal.players'),
		'heatmapEvents' => t('heatmap.events'),
		'heatmapKillers' => t('heatmap.killers'),
		'heatmapVictims' => t('heatmap.victims'),
		'heatmapInBounds' => t('heatmap.in_bounds'),
		'heatmapRequestFailed' => t('heatmap.request_failed', array(), 'Heatmap request failed'),
		'heatmapFlipX' => t('heatmap.flip_x'),
		'heatmapFlipY' => t('heatmap.flip_y'),
		'heatmapRotate' => t('heatmap.rotate'),
		'heatmapRotateLeft90' => t('heatmap.rotate_left_90'),
		'heatmapRotateRight90' => t('heatmap.rotate_right_90'),
		'heatmapAdmin' => array(
			'landmarks' => t('admin.task.heatmaps.landmarks'),
			'holdout' => t('admin.task.heatmaps.holdout'),
			'landmarksRequired' => t('admin.task.heatmaps.landmarks_required'),
			'registrationStatus' => t('admin.task.heatmaps.registration_accepted'),
			'candidateRefused' => t('admin.task.heatmaps.candidate_refused'),
			'previewRequired' => t('admin.task.heatmaps.preview_required'),
			'assetMismatch' => t('admin.task.heatmaps.asset_mismatch'),
			'registrationCoverage' => t('admin.task.heatmaps.registration_coverage'),
		),
		'heatmapExplorer' => array(
			'map' => t('heatmapExplorer.map'),
			'loading' => t('heatmapExplorer.loading'),
			'loaded' => t('heatmapExplorer.loaded'),
			'lens' => t('heatmapExplorer.lens'),
			'channel' => t('heatmapExplorer.channel'),
			'overview' => t('heatmapExplorer.overview'),
			'me' => t('heatmapExplorer.me'),
			'difference' => t('heatmapExplorer.difference'),
			'kills' => t('heatmapExplorer.kills'),
			'deaths' => t('heatmapExplorer.deaths'),
			'both' => t('heatmapExplorer.both'),
			'floor' => t('heatmapExplorer.floor'),
			'allFloors' => t('heatmapExplorer.allFloors'),
			'mapControls' => t('heatmapExplorer.mapControls'),
			'reset' => t('heatmapExplorer.reset'),
			'pan' => t('heatmapExplorer.pan'),
			'navigation' => t('heatmapExplorer.navigation'),
			'share' => t('heatmapExplorer.share'),
			'staticJpeg' => t('heatmapExplorer.staticJpeg'),
			'noscript' => t('heatmapExplorer.noscript'),
			'inspector' => t('heatmapExplorer.inspector'),
			'noCell' => t('heatmapExplorer.noCell'),
			'pinned' => t('heatmapExplorer.pinned'),
			'unpinned' => t('heatmapExplorer.unpinned'),
			'coverage' => t('heatmapExplorer.coverage'),
			'failed' => t('heatmapExplorer.failed'),
			'invalidUrl' => t('heatmapExplorer.invalidUrl'),
			'retry' => t('heatmapExplorer.retry'),
			'fallback' => t('heatmapExplorer.fallback'),
			'differenceBothCorrected' => t('heatmapExplorer.differenceBothCorrected'),
			'period' => t('heatmapExplorer.period'),
			'range7d' => t('heatmapExplorer.range7d'),
			'range30d' => t('heatmapExplorer.range30d'),
			'range90d' => t('heatmapExplorer.range90d'),
			'range365d' => t('heatmapExplorer.range365d'),
			'utcWindow' => t('heatmapExplorer.utcWindow'),
			'sample' => t('heatmapExplorer.sample'),
			'xyCoverage' => t('heatmapExplorer.xyCoverage'),
			'zCoverage' => t('heatmapExplorer.zCoverage'),
			'projectionCoverage' => t('heatmapExplorer.projectionCoverage'),
			'pointsUnavailable' => t('heatmapExplorer.pointsUnavailable'),
			'cells_fallback' => t('heatmapExplorer.cells_fallback'),
			'alignmentUnverified' => t('heatmapExplorer.alignmentUnverified'),
			'densityLegend' => t('heatmapExplorer.densityLegend'),
			'scaleLocked' => t('heatmapExplorer.scaleLocked'),
			'scaleAuto' => t('heatmapExplorer.scaleAuto'),
			'scaleReset' => t('heatmapExplorer.scaleReset'),
			'scaleSmooth' => t('heatmapExplorer.scaleSmooth'),
			'scaleCells' => t('heatmapExplorer.scaleCells'),
			'scalePoints' => t('heatmapExplorer.scalePoints'),
			'scaleDifference' => t('heatmapExplorer.scaleDifference'),
			'visiblePositions' => t('heatmapExplorer.visiblePositions'),
			'deathsLegend' => t('heatmapExplorer.deathsLegend'),
			'differenceLegend' => t('heatmapExplorer.differenceLegend'),
			'freshness' => t('heatmapExplorer.freshness'),
			'empty' => t('heatmapExplorer.empty'),
			'inspect' => t('heatmapExplorer.inspect'),
			'inspectSample' => t('heatmapExplorer.inspectSample'),
			'topWeapons' => t('heatmapExplorer.topWeapons'),
			'participants' => t('heatmapExplorer.participants'),
			'killers' => t('heatmapExplorer.killers'),
			'victims' => t('heatmapExplorer.victims'),
			'truncated' => t('heatmapExplorer.truncated'),
			'headshot' => t('heatmapExplorer.headshot'),
			'teamkill' => t('heatmapExplorer.teamkill'),
			'sceneSummary' => t('heatmapExplorer.sceneSummary'),
		),
		'hitbox' => array(
			'head' => t('literal.head'),
			'chest' => t('literal.chest'),
			'leftarm' => t('literal.left_arm'),
			'rightarm' => t('literal.right_arm'),
			'stomach' => t('literal.stomach'),
			'leftleg' => t('literal.left_leg'),
			'rightleg' => t('literal.right_leg'),
			'totalHits' => t('literal.total_hits'),
			'targets' => t('literal.targets'),
			'tuning' => t('hitbox.tuning'),
			'model' => t('hitbox.model'),
			'anchors' => t('hitbox.anchors'),
			'copyConfig' => t('hitbox.copy_config'),
			'reset' => t('hitbox.reset'),
			'resetConfirmation' => t('hitbox.reset_confirmation'),
			'resetApplied' => t('hitbox.reset_applied'),
			'copiedToClipboard' => t('hitbox.copied_to_clipboard'),
			'copyFailed' => t('hitbox.copy_failed'),
			'scale' => t('hitbox.scale'),
			'offsetX' => t('hitbox.offset_x'),
			'offsetY' => t('hitbox.offset_y'),
		),
	), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); ?>;
	</script>
	<script type="text/javascript" src="<?php echo INCLUDE_PATH; ?>/js/mootools.js"></script>
	<script type="text/javascript" src="<?php echo INCLUDE_PATH; ?>/js/SqueezeBox.js"></script>
	<script type="text/javascript" src="<?php echo INCLUDE_PATH; ?>/js/heatmap.js?v=<?php echo intval(@filemtime(INCLUDE_PATH . '/js/heatmap.js')); ?>"></script>
	<script type="text/javascript" src="<?php echo INCLUDE_PATH; ?>/js/heatmap-explorer.js?v=<?php echo intval(@filemtime(INCLUDE_PATH . '/js/heatmap-explorer.js')); ?>"></script>
<?php
	if ($g_options['playerinfo_tabs'] == '1') {
?>
	<script type="text/javascript" src="<?php echo INCLUDE_PATH; ?>/js/tabs.js"></script>
<?php
	}
?>
	<title>
<?php
	echo $g_options['sitename']; 
	foreach ($title as $t)
	{
		echo ' - ' . eHtml($t);
	}
?>
	</title>
</head>
<body> 
<?php
	//JS Check

	if (isset($_POST['js']) && $_POST['js']) {
		$_SESSION['nojs'] = 0;
	} else {
		if ((!isset($_SESSION['nojs'])) or ($_SESSION['nojs'] == 1)) {
			// Send javascript form - if they have javascript enabled it will POST the JS variable, and the code above will update their session variable
			$adminCsrfField = function_exists('admin_csrf_field') ? admin_csrf_field() : '';
			echo '
			<!-- Either this is your first visit in a while, or you don\'t have javascript enabled -->
			<form name="jsform" id="jsform" action="" method="post" style="display:none">
			<div>
			<input name="js" type="text" value="true" />' . $adminCsrfField . '
			<script type="text/javascript">
			document.jsform.submit();
			</script>
			</div>
			</form>'
			;
			$_SESSION['nojs'] = 1;
			$g_options['playerinfo_tabs'] = 0;
			$g_options['show_google_map'] = 0;
		}
	}
	
	// Determine if we should show SourceBans links/Forum links
	$extratabs = NULL;
	if ($g_options['sourcebans_address'] && file_exists($iconpath . "/title-sourcebans.png")) {
		$extratabs .= "<li><a href=\"". $g_options['sourcebans_address'] . "\" target=\"_blank\"><img src=\"" . $iconpath . "/title-sourcebans.png\" alt=\"SourceBans\" /></a></li>\n";
	}
	if ($g_options['forum_address'] && file_exists($iconpath . "/title-forum.png")) {
		$extratabs .= "<li><a href=\"" . $g_options['forum_address'] . "\" target=\"_blank\"><img src=\"" . $iconpath . "/title-forum.png\" alt=\"Forum\" /></a></li>\n";
	}

	$availableLanguages = available_langs();
?>
<div class="block">
	
	<div class="headerblock">
		<div class="title">
			<a href="<?php echo $g_options['scripturl']; ?>"><img src="<?php echo $iconpath; ?>/title.png" alt="HLstatsX Community Edition" title="HLstatsX Community Edition" /></a>
		</div>

<?php

		// Grab count of active games -- if 1, we won't show the games list icons
		$resultGames = $db->query("
			SELECT
				COUNT(code)
			FROM
				hlstats_Games
			WHERE
				hidden='0'
		");
		
		list($num_games) = $db->fetch_row($resultGames);
		
		if ($num_games > 1 && $g_options['display_gamelist'] == 1) {
?>
		<div class="header_gameslist"><?php @include(PAGE_PATH .'/gameslist.php'); ?></div>
<?php	
		}
?>
		<div class="headertabs">
			<ul>
				<li><a href="<?php echo $g_options['scripturl'] ?>"><img src="<?php echo $iconpath; ?>/title-contents.png" alt="<?php echo eHtml(t('ui.contents')); ?>" /></a></li>
				<li><a href="<?php echo $g_options['scripturl'] ?>?mode=search"><img src="<?php echo $iconpath; ?>/title-search.png" alt="<?php echo eHtml(t('ui.search')); ?>" /></a></li>
				<?php if ($extratabs) { print $extratabs; } ?>				
				<li><a href="<?php echo $g_options['scripturl'] ?>?mode=help"><img src="<?php echo $iconpath; ?>/title-help.png" alt="<?php echo eHtml(t('ui.help')); ?>" /></a></li>
			</ul>

		</div>
	</div>
	<div class="location" style="clear:both;width:100%;">
		<ul class="fNormal" style="float:left">
<?php
			if ($g_options['sitename'] && $g_options['siteurl'])
			{
				echo '<li><a href="http://' . preg_replace('/http:\/\//', '', $g_options['siteurl']) . '">'. $g_options['sitename'] . '</a> <span class="arrow">&raquo;</span></li>';
			}
			echo '<li><a href="http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'] . '">HLstatsX</a>';


			$i=0;
			foreach ($location as $l=>$url)
			{
				$url = preg_replace('/%s/', $g_options['scripturl'], $url);
				$url = preg_replace('/&/', '&amp;', $url);
				echo ' <span class="arrow">&raquo;</span></li><li>';
				if ($url) {
					echo '<a href="' . $url . '">' . eHtml($l) . '</a>';
				} else {
					echo '<strong>' . eHtml($l) . '</strong>';
				}
				$i++;
		}
?>			</li>
		</ul>

<?php 
		if ($g_options['display_style_selector'] == 1) {
?>
		<div class="fNormal" style="float:right;margin-left:12px;">
			<form name="style_selection" id="style_selection" action="" method="post"> <?php echo function_exists('admin_csrf_field') ? admin_csrf_field() : ''; ?><?php echo eHtml(t('ui.style')); ?>:
				<select name="stylesheet" onchange="document.style_selection.submit()"> 
				<?php 
					$d = dir('styles'); 
					while (false !== ($e = $d->read())) { 
						if (is_file("styles/$e") && ($e != '.') && ($e != '..') && $e != $g_options['style']) { 
							$ename = ucwords(strtolower(str_replace(array('_','.css'), array(' ',''), $e))); 
							$styles[$e] = $ename; 
						} 
					}
					$d->close(); 
					asort($styles); 
					$styles = array_merge(array($g_options['style'] => t('ui.default')),$styles);
					foreach ($styles as $e => $ename) { 
						$sel = ''; 
						if ($e == $selectedStyle) $sel = ' selected="selected"'; 
						echo "\t\t\t\t<option value=\"$e\"$sel>$ename</option>\n"; 
					} ?> 
				</select> 
			</form> 
		</div> 
<?php
		}
?>
		<div class="fNormal" style="float:right;">
			<form name="language_selection" id="language_selection" action="<?php echo eHtml($g_options['scripturl']); ?>" method="get">
				<?php foreach ($_GET as $param => $value) :
					if ($param === 'lang' || is_array($value)) {
						continue;
					}
				?>
					<input type="hidden" name="<?php echo eHtml($param); ?>" value="<?php echo eHtml($value); ?>" />
				<?php endforeach; ?>
				<?php echo eHtml(t('ui.language')); ?>:
				<select name="lang" onchange="document.language_selection.submit()">
					<?php foreach ($availableLanguages as $languageCode => $languageMeta) :
						$selected = ($languageCode === current_lang()) ? ' selected="selected"' : '';
					?>
						<option value="<?php echo eHtml($languageCode); ?>"<?php echo $selected; ?>><?php echo eHtml($languageMeta['label']); ?></option>
					<?php endforeach; ?>
				</select>
			</form>
		</div>
	</div>
	<div class="location_under" style="clear:both;width:100%;"></div>
</div>

<br />
      
<div class="content" style="clear:both;">
<?php
	global $mode;
	if ($g_options['bannerdisplay'] != 0 && ($mode == 'contents' || $g_options['bannerdisplay']==1)) {
?>    
	<div class="block" style="text-align:center;">
		<img src="<?php echo ((strncmp($g_options['bannerfile'], 'http:/', 6) == 0)?$g_options['bannerfile']:IMAGE_PATH.'/'.$g_options['bannerfile']); ?>" alt="Banner" />
	</div>
<?php
	}
?>        

<?php

	if ($game != '') {

?>    
		<nav>
		<ul class="fancyNav">
			<li><a href="<?php echo $g_options['scripturl']  . "?game=$game";  ?>" class="fHeading"><?php echo eHtml(t('literal.servers')); ?></a></li>

<?php
	if ($g_options['nav_globalchat']==1) {
?>
			<li><a href="<?php echo $g_options['scripturl']  . "?mode=chat&amp;game=$game";  ?>" class="fHeading"><?php echo eHtml(t('literal.chat')); ?></a></li>
<?php
	}
?>
			<li><a href="<?php echo $g_options['scripturl'] . "?mode=players&amp;game=$game"; ?>" class="fHeading"><?php echo eHtml(t('literal.players')); ?></a></li>
			<li><a href="<?php echo $g_options['scripturl'] . "?mode=clans&amp;game=$game"; ?>" class="fHeading"><?php echo eHtml(t('literal.clans')); ?></a></li>

<?php
	if ($g_options["countrydata"]==1) {
?>
			<li><a href="<?php echo $g_options['scripturl']  . "?mode=countryclans&amp;game=$game&amp;sort=nummembers";  ?>" class="fHeading"><?php echo eHtml(t('literal.countries')); ?></a></li>
<?php
	}
?>
			<li><a href="<?php echo $g_options['scripturl'] . "?mode=awards&amp;game=$game"; ?>" class="fHeading"><?php echo eHtml(t('literal.awards')); ?></a></li>
<?php
	// look for actions
	$db->query("SELECT game FROM hlstats_Actions WHERE game='".$game."' LIMIT 1");
	if ($db->num_rows()>0) {
?> 
			<li><a href="<?php echo $g_options['scripturl'] . "?mode=actions&amp;game=$game"; ?>" class="fHeading"><?php echo eHtml(t('literal.actions')); ?></a></li>
<?php
	}
?>
			<li><a href="<?php echo $g_options['scripturl'] . "?mode=weapons&amp;game=$game"; ?>" class="fHeading"><?php echo eHtml(t('literal.weapons')); ?></a></li>
				<li><a href="<?php echo $g_options['scripturl'] . "?mode=maps&amp;game=$game"; ?>" class="fHeading"><?php echo eHtml(t('literal.maps')); ?></a></li>
<?php
	$result = $db->query("SELECT game from hlstats_Roles WHERE game='$game' AND hidden = '0'");
	$numitems = $db->num_rows($result);
	if ($numitems > 0) {
?>
			<li><a href="<?php echo $g_options['scripturl'] . "?mode=roles&amp;game=$game"; ?>" class="fHeading"><?php echo eHtml(t('literal.roles')); ?></a></li>
<?php
	}
	if ($g_options['nav_cheaters'] == 1) {
?>
			<li><a href="<?php echo $g_options['scripturl'] . "?mode=bans&amp;game=$game"; ?>" class="fHeading"><?php echo eHtml(t('literal.bans', array(), 'Bans')); ?></a></li>
<?php
	} 
?>
	</ul></nav>
<?php
	}
?>  


